vich_uploader:
    db_driver: orm

    mappings:
        images_prod:
            uri_prefix:         '%images_prod%'
            upload_destination: '%kernel.project_dir%/public%images_prod%'
        


